import MarkdownIt from "markdown-it";
const BLOCKED_URL_PREFIXES = ["javascript:", "data:", "vbscript:"];

export const isSafeMarkdownUrl = (url) => {
  const trimmed = String(url || "").trim();
  if (!trimmed) return false;
  const lower = trimmed.toLowerCase();
  for (const prefix of BLOCKED_URL_PREFIXES) {
    if (lower.startsWith(prefix)) return false;
  }
  return /^(https?:\/\/|mailto:|#|\/(?!\/))/i.test(trimmed);
};

const md = new MarkdownIt({ html: false, breaks: false, linkify: false, typographer: false });

const defaultLinkOpen = md.renderer.rules.link_open;
md.renderer.rules.link_open = (tokens, idx, options, env, self) => {
  const token = tokens[idx];
  const hrefIndex = token.attrIndex("href");
  if (hrefIndex >= 0) {
    const href = token.attrs[hrefIndex][1];
    if (!isSafeMarkdownUrl(href)) {
      token.attrs[hrefIndex][1] = "#blocked";
      token.attrs.push(["rel", "noreferrer"]);
    } else {
      token.attrs.push(["target", "_blank"]);
      token.attrs.push(["rel", "noreferrer"]);
    }
  }
  if (defaultLinkOpen) return defaultLinkOpen(tokens, idx, options, env, self);
  return self.renderToken(tokens, idx, options);
};

export function renderMd(text) {
  if (!text) return "";
  // Raw HTML is disabled above. All markup in this result is generated by
  // markdown-it, while the custom link renderer constrains user URLs.
  return md.render(String(text));
}

export function bodyToPreviewHtml(value) {
  return renderMd(value);
}

export function extractTags(body) {
  if (!body) return [];
  const raw = String(body);
  // Replace escaped \#tag with sentinel chars so only unescaped #tag instances
  // match below. The sentinel survives MarkdownIt and the # is removed.
  const safe = raw.replace(/\\#([\p{L}\p{N}_-]+)/gu, "\u007F\u007F$1");

  const tokens = md.parse(safe, {});
  const found = new Map();
  for (const block of tokens) {
    if (block.type === "fence" || block.type === "code_block") continue;
    if (!block.children) continue;
    for (const child of block.children) {
      if (child.type !== "text") continue;
      const content = child.content;
      const TAG_RE = /#([\p{L}\p{N}_-]+)/gu;
      let m;
      while ((m = TAG_RE.exec(content)) !== null) {
        const display = m[1];
        const key = display.toLowerCase();
        if (!found.has(key)) {
          found.set(key, Array.from(display));
        }
      }
    }
  }
  return Array.from(found.entries())
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([key, displayChars]) => {
      let display = displayChars.join("");
      return { key, display };
    });
}
